#!/usr/bin/env bash
# host-setup.sh — re-apply changi Proxmox host config after a fresh install
# Generated by _scripts/generate-host-setup.sh — re-run to update
# Run on changi as root

set -euo pipefail

echo "=== 1. Storage pools ==="
# pbs storage: replace <TOKEN_SECRET> with the actual PBS API token secret
pvesm add pbs pbs --datastore datastore --server 192.168.xx.xx --content backup --prune-backups keep-all=1 --username proxmox@pbs

echo ""
echo "=== 2. Backup jobs ==="
pvesh create /cluster/backup --vmid 1001,1002,1003 --storage pbs --schedule 0:00 --mode snapshot

echo ""
echo "=== 3. Network interfaces ==="
# Review before applying — verify interface names match the hardware
cat > /etc/network/interfaces << 'EOF'
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

auto lo
iface lo inet loopback

iface nic0 inet manual
    post-up /usr/sbin/ethtool -K $IFACE tso off gso off gro off

iface nic1 inet manual

iface wlp2s0 inet manual

auto vmbr0
iface vmbr0 inet static
	address 192.168.xx.xx/24
	gateway 192.168.xx.xx
	bridge-ports nic0
	bridge-stp off
	bridge-fd 0

source /etc/network/interfaces.d/*
EOF
ifreload -a

echo ""
echo "Done. Verify in Proxmox UI: Storage, Backup, Network."
