#!/usr/bin/env bash
# generate-host-setup.sh — capture current Proxmox host config → changi/setup-scripts/host-setup.sh
# Requires: homelab-admin user in www-data group on changi (reads /etc/pve/ via pmxcfs)
# Usage: bash _scripts/generate-host-setup.sh

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
OUTPUT="$REPO_DIR/changi/_setup/changi-setup.sh"
mkdir -p "$(dirname "$OUTPUT")"

# Emit pvesm add commands for non-default storages (local and local-lvm are recreated automatically)
storage_commands() {
  python3 -c "
import re

with open('/etc/pve/storage.cfg') as f:
    content = f.read()

skip = {'local', 'local-lvm'}
for block in re.split(r'\n(?=\S)', content.strip()):
    lines = block.strip().splitlines()
    if not lines:
        continue
    header = lines[0].split()
    if len(header) < 2:
        continue
    stype, sname = header[0].rstrip(':'), header[1]
    if sname in skip:
        continue
    opts = {}
    for line in lines[1:]:
        parts = line.strip().split(None, 1)
        if len(parts) == 2:
            opts[parts[0]] = parts[1]
    cmd = f'pvesm add {stype} {sname}'
    for k, v in opts.items():
        if k == 'fingerprint':
            continue  # regenerated on first connect
        if k == 'password':
            v = '\"<TOKEN_SECRET>\"'
        cmd += f' --{k} {v}'
    print(cmd)
"
}

# Emit pvesh create commands for all scheduled backup jobs (read from /etc/pve/jobs.cfg)
backup_commands() {
  python3 -c "
import re

try:
    with open('/etc/pve/jobs.cfg') as f:
        content = f.read()
except FileNotFoundError:
    exit(0)

for block in re.split(r'\n(?=\S)', content.strip()):
    lines = block.strip().splitlines()
    if not lines:
        continue
    header = lines[0].split()
    if len(header) < 2 or header[0].rstrip(':') != 'vzdump':
        continue
    opts = {}
    for line in lines[1:]:
        parts = line.strip().split(None, 1)
        if len(parts) == 2:
            opts[parts[0]] = parts[1]
    cmd = 'pvesh create /cluster/backup'
    for k in ('vmid', 'storage', 'schedule', 'mode', 'compress', 'mailto'):
        v = opts.get(k)
        if v:
            # jobs.cfg uses spaces between vmids; pvesh expects commas
            if k == 'vmid':
                v = v.replace(' ', ',')
            cmd += f' --{k} {v}'
    print(cmd)
"
}

{
  cat << 'HEADER'
#!/usr/bin/env bash
# host-setup.sh — re-apply changi Proxmox host config after a fresh install
# Generated by _scripts/generate-host-setup.sh — re-run to update
# Run on changi as root

set -euo pipefail
HEADER

  printf '\necho "=== 1. Storage pools ==="\n'
  printf '# pbs storage: replace <TOKEN_SECRET> with the actual PBS API token secret\n'
  storage_commands

  printf '\necho ""\necho "=== 2. Backup jobs ==="\n'
  backup_commands

  printf '\necho ""\necho "=== 3. Network interfaces ==="\n'
  printf '# Review before applying — verify interface names match the hardware\n'
  printf "cat > /etc/network/interfaces << 'EOF'\n"
  cat /etc/network/interfaces
  printf 'EOF\nifreload -a\n'

  printf '\necho ""\necho "Done. Verify in Proxmox UI: Storage, Backup, Network."\n'
} > "$OUTPUT"

chmod +x "$OUTPUT"
echo "Done — changi/host-setup.sh written."
